# safelist
# branches:
#   only:
#     - dev

language: python
python:
  - '3.6'

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="cafe.settings.travis"

services:
  - postgresql

addons:
  postgresql: "9.4"

script:
  - make cov_test