version: '3'

services:

  cafe_nginx:
    container_name: cafe_nginx
    restart: always
    image: nginx
    depends_on:
      - cafe_py
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    ports:
      - '8061:80'
    networks:
      - traefik
    labels:
      - 'traefik.enable=true'
      - 'traefik.backend=cafe_nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:staging.cafe-programmation.fr'

  cafe_py:
    container_name: cafe_py
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.prod
    depends_on:
      - cafe_db
    links:
      - cafe_db:database
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - ./:/usr/src/app
    networks:
      - traefik

  cafe_db:
    container_name: cafe_db
    restart: always
    image: postgres
    networks:
      - traefik

networks:
  traefik:
    external:
      name: proxy